<?php

module_load_include('module', 'settings_provider');
$module_path = drupal_get_path('module', 'dynamics_ax_settings_provider');
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/forms/admin.inc');
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/DynamicsAXConnectionDriver.php');

use com\mainone\middleware\DynamicsAXConnectionDriver;

function dynamics_ax_settings_provider_connection_driver_dynamics_ax_alter(&$container) {
    $driver = new DynamicsAXConnectionDriver(function($x){
        $return = mware_connection_driver__get_driver($x);
        return $return;
    });

    $defs = dynamics_ax_settings_provider__get_entity_definitions();
    $driver->setEntities($defs);
    $container['dynamics_ax'] = $driver;
}

/**
 * Implements hook_permission
 * @return array
 */
function dynamics_ax_settings_provider_permission() {
    $permission = [];
    
    return $permission;
}

/**
 * Confirms if a user should be allowed to access something.
 * @param type $args
 * @return boolean
 */
function dynamics_ax_settings_provider__user_access($args) {
    return true;
}

/**
 * Returns all the entity definitions implemented in Dynamics AX.
 * @return type
 */
function dynamics_ax_settings_provider__get_entity_definitions() {
    return [
        'cust_table' => [
            'internal_name' => 'CustTable',
            'fields' => [
                'RECID' => [
                    'preferred_name' => 'Id',
                    'type' => 'string',
                    'mandatory' => 1,
                ],
                'GCID' => [
                    'preferred_name' => 'Customer',
                    'type' => 'string',
                    'mandatory' => 1
                    ,'relationship' => [
                        'local_field' => 'Customer'
                        , 'remote_field' => 'GCID'
                        , 'remote_type'=> 'parent'
                        , 'remote_entity'=> 'account'
                        , 'remote_driver' => 'salesforce'
                    ],
                ],
                'MODIFIEDDATETIME' => [
                    'preferred_name' => 'Modified',
                    'type' => 'datetime',
                ],
                'CREATEDDATETIME' => [
                    'preferred_name' => 'Created',
                    'type' => 'datetime',
                ],
                'ACCOUNTNUM' => [
                    'preferred_name' => 'AccountNumber'
                    , 'type' => 'string'
                ],
                'DATAAREAID' => [
                    'preferred_name' => 'DataArea',
                    'type' => 'string',
                ],
                '_TRANSACTIONS' => [
                    'preferred_name' => 'Transactions',
                    'type' => 'detail',
                    'lookup_entity' => 'cust_trans',
                    'relationship' => [
                        'local_field' => 'AccountNumber',
                        'remote_field' => 'AccountNumber',
                        'remote_type' => 'child'
                    ],
                ],
            ]
        ]
        ,'cust_trans' => [
            'internal_name' => 'CustTrans',
            'fields' => [
                'RECID' => [
                    'preferred_name' => 'Id',
                    'type' => 'int',
                    'mandatory' => 1,
                ],
                'MODIFIEDDATETIME' => [
                    'preferred_name' => 'Modified',
                    'type' => 'datetime',
                ],
                'CREATEDDATETIME' => [
                    'preferred_name' => 'Created',
                    'type' => 'datetime',
                ],
                'ACCOUNTNUM' => [
                    'preferred_name' => 'AccountNumber',
                    'type' => 'string'                    
                    , 'relationship' => [
                        'local_field' => 'AccountNumber'
                        , 'remote_field' => 'AccountNumber'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'cust_table'
                    ]
                    , 'mandatory' => 1
                ],
                'AMOUNTCUR' => [
                    'preferred_name' => 'Amount',
                    'type' => 'datetime',
                ],
                'SETTLEAMOUNTCUR' => [
                    'preferred_name' => 'AmountSettled',
                    'type' => 'int',
                ],
                'SETTLEMENT' => [
                    'preferred_name' => 'Settlement',
                    'type' => 'int',
                ],
                'TXT' => [
                    'preferred_name' => 'Narrative',
                    'type' => 'string',
                ],
                'TRANSTYPE' => [
                    'preferred_name' => 'TransactionType',
                    'type' => 'int',
                ],
                'APPROVED' => [
                    'preferred_name' => 'ApprovalStatus',
                    'type' => 'int',
                ],
                'CORRECT' => [
                    'preferred_name' => 'IsCorrection',
                    'type' => 'int',
                ],
                'CANCELLEDPAYMENT' => [
                    'preferred_name' => 'IsCancelled',
                    'type' => 'int',
                ],
                'CURRENCYCODE' => [
                    'preferred_name' => 'CurrencyCode',
                    'type' => 'string',
                ],
                'EXCHRATE' => [
                    'preferred_name' => 'ExchangeRate',
                    'type' => 'int',
                ],
                'TRANSDATE' => [
                    'preferred_name' => 'TransactionDate',
                    'type' => 'datetime',
                ],
                'CLOSED' => [
                    'preferred_name' => 'Closed',
                    'type' => 'datetime',
                ],
                'DUEDATE' => [
                    'preferred_name' => 'DueDate',
                    'type' => 'datetime',
                ],
                'INVOICE' => [
                    'preferred_name' => 'InvoiceNumber',
                    'type' => 'string',
                ],
                'VOUCHER' => [
                    'preferred_name' => 'VoucherNumber',
                    'type' => 'string',
                ],
                'LASTSETTLEVOUCHER' => [
                    'preferred_name' => 'LastSettlementVoucherNumber',
                    'type' => 'string',
                ],
                'PAYMID' => [
                    'preferred_name' => 'PaymentId',
                    'type' => 'string',
                ],
                'DATAAREAID' => [
                    'preferred_name' => 'EntityName',
                    'type' => 'string',
                ],
                '_INVOICE_INFORMATION' => [
                    'preferred_name' => 'InvoiceInformation'
                    , 'type' => 'detail'
                    , 'lookup_entity' => 'cust_trans'
                    , 'relationship' => [
                        'local_field' => 'LastSettlementVoucherNumber',
                        'remote_field' => 'VoucherNumber',
                        'remote_type' => 'parent',
                        'filter' => 'InvoiceNumber ne $NULL$'
                    ],
                ],
                '_INVOICE' => [
                    'preferred_name' => 'Invoice',
                    'type' => 'detail',
                    'lookup_entity' => 'cust_invoice_table',
                    'relationship' => [
                        'local_field' => 'InvoiceNumber',
                        'remote_field' => 'InvoiceNumber',
                        'remote_type' => 'parent',
                        'filter' => 'InvoiceNumber ne $NULL$'
                    ],
                ],
                '_CUSTOMER' => [
                    'preferred_name' => 'Customer',
                    'type' => 'detail',
                    'lookup_entity' => 'cust_table',
                    'relationship' => [
                        'local_field' => 'AccountNumber',
                        'remote_field' => 'AccountNumber',
                        'remote_type' => 'parent'
                    ],
                ],
                '_TRANSACTIONS' => [
                    'preferred_name' => 'Transactions',
                    'type' => 'detail',
                    'lookup_entity' => 'cust_trans',
                    'relationship' => [
                        'local_field' => 'VoucherNumber',
                        'remote_field' => 'LastSettlementVoucherNumber',
                        'remote_type' => 'child'
                    ],
                ],
            ]
        ]
        ,'cust_invoice_table' => [
            'internal_name' => 'CustInvoiceTable',
            'fields' => [
                'RECID' => [
                    'preferred_name' => 'Id',
                    'type' => 'int',
                    'mandatory' => 1,
                ],
                'MODIFIEDDATETIME' => [
                    'preferred_name' => 'Modified',
                    'type' => 'datetime',
                ],
                'CREATEDDATETIME' => [
                    'preferred_name' => 'Created',
                    'type' => 'datetime',
                ],
                'DUEDATE' => [
                    'preferred_name' => 'DueDate',
                    'type' => 'datetime',
                ],
                'ENDDATE' => [
                    'preferred_name' => 'EndDate',
                    'type' => 'datetime',
                ],
                'ITEMPAIDFOR' => [
                    'preferred_name' => 'ItemPaidFor',
                    'type' => 'string',
                ],
                'INVOICEACCOUNT' => [
                    'preferred_name' => 'AccountNumber',
                    'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'AccountNumber'
                        , 'remote_field' => 'AccountNumber'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'cust_table'
                    ]
                    , 'mandatory' => 1
                ],
                'INVOICEID' => [
                    'preferred_name' => 'InvoiceNumber',
                    'type' => 'string',
                ],
                '_ENTITY' => [
                    'preferred_name' => 'EntityName',
                    'type' => 'string',
                ],
                '_CUSTOMER' => [
                    'preferred_name' => 'Customer',
                    'type' => 'detail',
                    'lookup_entity' => 'cust_table',
                    'relationship' => [
                        'local_field' => 'AccountNumber',
                        'remote_field' => 'AccountNumber',
                        'remote_type' => 'parent'
                    ],
                ]
                ,'_LINES' => [
                    'preferred_name' => 'Lines',
                    'type' => 'detail',
                    'lookup_entity' => 'cust_invoice_line',
                    'relationship' => [
                        'local_field' => 'Id',
                        'remote_field' => 'InvoiceId',
                        'remote_type' => 'child'
                    ],
                ],
                '_INVOICE_INFO' => [
                    'preferred_name' => 'InvoiceInformation',
                    'type' => 'detail',
                    'lookup_entity' => 'cust_trans',
                    'relationship' => [
                        'local_field' => 'InvoiceNumber',
                        'remote_field' => 'InvoiceNumber',
                        'filter' => 'InvoiceNumber ne $NULL$',
                        'remote_type' => 'parent'
                    ],
                ],
            ]
        ]
        , 'cust_invoice_line' => [
            'internal_name' => 'CustInvoiceLine',
            'fields' => [
                'RECID' => [
                    'preferred_name' => 'Id',
                    'type' => 'int',
                    'mandatory' => 1,
                ],
                'MODIFIEDDATETIME' => [
                    'preferred_name' => 'Modified',
                    'type' => 'datetime',
                ],
                'CREATEDDATETIME' => [
                    'preferred_name' => 'Created',
                    'type' => 'datetime',
                ]
                , 'PARENTRECID' => [
                    'preferred_name' => 'Invoice',
                    'type' => 'int',
                    'lookup_entity' => 'cust_invoice_table',
                    'relationship' => [
                        'local_field' => 'Invoice',
                        'remote_field' => 'Id',
                        'remote_type' => 'parent'
                    ],
                ]
                , 'SFCUSTOMERPRODUCTID' => [
                    'preferred_name' => 'CustomerProduct',
                    'type' => 'string',
                    'relationship' => [
                        'local_field' => 'CustomerProduct',
                        'remote_field' => 'Id',
                        'remote_type' => 'parent'
                        , 'remote_entity' => 'customer_product'
                        , 'remote_driver' => 'salesforce'
                    ],
                ]
                , 'SFOPPORTUNITYID' => [
                    'preferred_name' => 'Opportunity',
                    'type' => 'string',
                    'relationship' => [
                        'local_field' => 'Opportunity',
                        'remote_field' => 'Id',
                        'remote_type' => 'parent'
                        , 'remote_entity' => 'opportunity'
                        , 'remote_driver' => 'salesforce'
                    ],
                ]
                , 'DATAAREAID' => [
                    'preferred_name' => 'DataArea',
                    'type' => 'string',
                ]
            ]
        ]
    ];
}
