<?php

require_once 'forms/admin.inc';

/**
 * Implement hook_menu().
 */
function dynamics_ax_settings_provider_menu() {
    $items = [];

    return $items;
}

/**
 * Implements hook_permission
 * @return array
 */
function dynamics_ax_settings_provider_permission() {
    $permission = [];
    return $permission;
}

function dynamics_ax_settings_provider__user_access($args) {
    return true;
}

/**
 * Implements hook_library
 * @return array
 */
function dynamics_ax_settings_provider_library() {
    $libraries = array();

    return $libraries;
}

function dynamics_ax_settings_provider__get_settings(){
    $s = new stdClass();
    $s->URL = variable_get('DYNAMICS_AX_SETTINGS_ENDPOINT_URL');
    $s->Function = variable_get('DYNAMICS_AX_SETTINGS_TABLE_FUNCTION');
    $s->Entities = variable_get('DYNAMICS_AX_SETTINGS_ENTITIES');
    return $s;
}