<?php

module_load_include('module', 'settings_provider');
$module_path = drupal_get_path('module', 'd365_connection_driver');
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/forms/admin.inc');
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/D365ConnectionDriver.php');

use com\mainone\middleware\D365ConnectionDriver;

/**
 * Implements hook_permission
 * @return array
 */
function d365_connection_driver_permission()
{
    $permission = [];
    return $permission;
}

function d365_connection_driver_connection_driver_d365_alter(&$container)
{
    $connection_settings = d365_connection_driver__get_settings();
    $driver = new D365ConnectionDriver(function ($x) {
        return mware_connection_driver__get_driver($x);
    }, function () {
    }, 'd365', $connection_settings);

    $defs = d365_connection_driver__get_entity_definitions_local();
    $driver->setEntities(($defs));
    $driver->addUtilityFunction('date_sync_util', function(){
            $args = func_get_args();
            $return = module_invoke('settings_provider', '_update_cache', ...$args);
    });
    $container['d365'] = $driver;
}

function d365_connection_driver__user_access($args)
{
    return true;
}

/**
 * Returns the connection settings with which to connect to d365.
 * @return \stdClass
 */
function d365_connection_driver__get_settings($settings = 'default')
{
    $s = new stdClass();
    $sT = $settings == 'default' ? variable_get('D365_SETTINGS_USE_PRODUCTION', false) : ($settings == 'production' ? true : false);

    if ($sT == false) {
        $s->URL = variable_get('D365_SANDBOX_SETTINGS_ENDPOINT_URL');
        $s->Username = variable_get('D365_SANDBOX_SETTINGS_USERNAME');
        $s->Password = variable_get('D365_SANDBOX_SETTINGS_PASSWORD');
        $s->GrantType = variable_get('D365_SANDBOX_SETTINGS_GRANT_TYPE');
        $s->ClientID = variable_get('D365_SANDBOX_SETTINGS_CLIENT_ID');
        $s->ClientSecret = variable_get('D365_SANDBOX_SETTINGS_CLIENT_SECRET');
        $s->ProxyServer = variable_get('D365_PROXY_SERVER');
        $s->ProxyServerPort = variable_get('D365_PROXY_SERVER_PORT');
        $s->UseProxyServer = variable_get('D365_SANDBOX_SETTINGS_USE_PROXY');
    } else {
        $s->URL = variable_get('D365_SETTINGS_ENDPOINT_URL');
        $s->Username = variable_get('D365_SETTINGS_USERNAME');
        $s->Password = variable_get('D365_SETTINGS_PASSWORD');
        $s->GrantType = variable_get('D365_SETTINGS_GRANT_TYPE');
        $s->ClientID = variable_get('D365_SETTINGS_CLIENT_ID');
        $s->ClientSecret = variable_get('D365_SETTINGS_CLIENT_SECRET');
        $s->ProxyServer = variable_get('D365_PROXY_SERVER');
        $s->ProxyServerPort = variable_get('D365_PROXY_SERVER_PORT');
        $s->UseProxyServer = variable_get('D365_SETTINGS_USE_PROXY');
    }
    return $s;
}

/**
 * Returns entity definitions that have been marked as cacheable to the specified entity.
 *
 * @param String $targetDriver the connection driver to use to retrieve the cache.
 * @return void
 */
function d365_connection_driver__get_cached_entity_definitions($targetDriver)
{
    return settings_provider__format_cached_definition('d365', $targetDriver, function(){
        $args = func_get_args();
        $return = d365_connection_driver__get_entity_definitions_local(...$args);
        return $return;
    });
}

function d365_connection_driver__get_entity_definitions_local(){
    return d365_connection_driver__get_entity_definitions(...func_get_args())['d365'];
}

/**
 * Returns the full definition of an entity or the definition of the specified component.
 * Components include: fields, internal_name
 * @param string $entity_name
 * @param string $component
 * @return array
 */
function d365_connection_driver__get_entity_definitions()
{
    $in_store = variable_get('D365_DRIVER_OBJECTS');

    if(is_null($in_store)){      

        $in_store = ['d365'=> [
            'cust_table' => [
                'internal_name' => 'CustTable'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1,
                    ]
                    , 'GCID' => [
                        'preferred_name' => 'Customer'
                        , 'type' => 'string'
                        , 'mandatory' => 1
                        , 'relationship' => [
                            'local_field' => 'Customer'
                            , 'preferred_local_key_name' => 'GCID'
                            , 'remote_field' => 'GCID'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'account'
                            , 'remote_driver' => 'salesforce'
                        ]
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                    , 'PARTY' => [
                        'preferred_name' => 'RootAccount'
                        , 'type' => 'int'
                        , 'relationship' => [
                            'local_field' => 'RootAccount'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'preferred_local_key_name' => 'RootAccountId'
                            , 'remote_entity' => 'rootaccount'
                        ]
                    ]
                    , 'ACCOUNTNUM' => [
                        'preferred_name' => 'AccountNumber'
                        , 'type' => 'string'
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string',
                    ]
                    , '_TRANSACTIONS' => [
                        'preferred_name' => 'Transactions'
                        , 'type' => 'detail'
                        , 'lookup_entity' => 'cust_trans'
                        , 'relationship' => [
                            'local_field' => 'AccountNumber'
                            , 'remote_field' => 'AccountNumber'
                            , 'remote_type' => 'child'
                        ],
                    ]
                    , '_INVOICES' => [
                        'preferred_name' => 'Invoices'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'AccountNumber'
                            , 'remote_field' => 'AccountNumber'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'cust_invoice_table'
                            , 'filter' => ' and IsPosted eq 1'
                        ],
                    ]
                ]
            ]
            , 'rootaccount' => [
                'internal_name' => 'DirPartyTable'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'GCID' => [
                        'preferred_name' => 'Customer'
                        , 'type' => 'string'
                        , 'mandatory' => 1
                        , 'relationship' => [
                            'local_field' => 'Customer'
                            , 'remote_field' => 'GCID'
                            , 'preferred_local_key_name' => 'GCID'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'account'
                            , 'remote_driver' => 'salesforce'
                        ]
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string',
                    ]
                    , 'NAME' => [
                        'preferred_name' => 'Name'
                        , 'type' => 'string'
                        , 'mandatory' => 1
                    ]
                    , '_ACCOUNTS' => [
                        'preferred_name' => 'Accounts'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'RootAccount'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'cust_table'
                        ]
                    ]
                ]
            ]
            , 'dataarea' => [
                'internal_name' => 'DataArea'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'ID' => [
                        'preferred_name' => 'DataAreaId'
                        , 'type' => 'string'
                        , 'mandatory' => 1
                    ]
                    , 'ISVIRTUAL' => [
                        'preferred_name' => 'IsVirtual'
                        , 'type' => 'string'
                    ]
                    , 'NAME' => [
                        'preferred_name' => 'Name'
                        , 'type' => 'string'
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                ]
            ]
            , 'globalcustomerinformation' => [
                'internal_name' => 'globalcustomerinformation'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'ACCOUNTNAME' => [
                        'preferred_name' => 'Name'
                        , 'type' => 'string'
                        , 'mandatory' => 1
                    ]
                    , 'GLOBALID' => [
                        'preferred_name' => 'GCID'
                        , 'type' => 'string'
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string',
                    ]
                    , 'STATUS' => [
                        'preferred_name' => 'Status'
                        , 'type' => 'string'
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                ]
            ]
            , 'paymentterm' => [
                'internal_name' => 'paymterm'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'PAYMTERMID' => [
                        'preferred_name' => 'PaymentTermId'
                        , 'type' => 'string'
                        , 'mandatory' => 1
                    ]
                    , 'DESCRIPTION' => [
                        'preferred_name' => 'Description'
                        , 'type' => 'string'
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                ]
            ]
            , 'cust_trans' => [
                'internal_name' => 'CustTrans'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1,
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime'
                    ]
                    , 'ACCOUNTNUM' => [
                        'preferred_name' => 'Account'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'Account'
                            , 'preferred_local_key_name' => 'AccountNumber'
                            , 'remote_field' => 'AccountNumber'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_table'
                        ]
                        , 'mandatory' => 1
                    ]
                    , 'AMOUNTCUR' => [
                        'preferred_name' => 'Amount'
                        , 'type' => 'decimal',
                    ]
                    , 'AMOUNTMST' => [
                        'preferred_name' => 'StandardAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'REPORTINGCURRENCYAMOUNT' => [
                        'preferred_name' => 'ReportedAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'SETTLEAMOUNTCUR' => [
                        'preferred_name' => 'AmountSettled'
                        , 'type' => 'decimal',
                    ]
                    , 'SETTLEAMOUNTMST' => [
                        'preferred_name' => 'StandardAmountSettled'
                        , 'type' => 'decimal',
                    ]
                    , 'SETTLEAMOUNTREPORTING' => [
                        'preferred_name' => 'ReportedAmountSettled'
                        , 'type' => 'decimal',
                    ]
                    , 'SETTLEMENT' => [
                        'preferred_name' => 'Settlement'
                        , 'type' => 'int',
                    ]
                    , 'TXT' => [
                        'preferred_name' => 'Narrative'
                        , 'type' => 'string',
                    ]
                    , 'TRANSTYPE' => [
                        'preferred_name' => 'TransactionType'
                        , 'type' => 'int'
                    ]
                    , 'APPROVED' => [
                        'preferred_name' => 'IsApproved'
                        , 'type' => 'int'
                    ]
                    , 'APPROVER' => [
                        'preferred_name' => 'ApprovedBy'
                        , 'type' => 'int'
                    ]
                    , 'CORRECT' => [
                        'preferred_name' => 'IsCorrection'
                        , 'type' => 'int'
                    ]
                    , 'PAYMMETHOD' => [
                        'preferred_name' => 'PaymentMethod'
                        , 'type' => 'string'
                    ]
                    , 'OFFSETRECID' => [
                        'preferred_name' => 'OffsetTransaction'
                        , 'type' => 'int'
                        , 'relationship' => [
                            'local_field' => 'OffsetTransaction'
                            , 'preferred_local_key_name' => 'OffsetTransactionId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            // , 'filter' => 'TransactionType eq 8'
                            , 'remote_entity' => 'cust_trans'
                        ]
                    ]
                    , 'CANCELLEDPAYMENT' => [
                        'preferred_name' => 'IsCancelled'
                        , 'type' => 'int'
                    ]
                    , 'CURRENCYCODE' => [
                        'preferred_name' => 'CurrencyCode'
                        , 'type' => 'string',
                    ]
                    , 'LASTEXCHADJRATEREPORTING' => [
                        'preferred_name' => 'ReportedExchangeRate'
                        , 'type' => 'decimal'
                    ]
                    , 'EXCHRATE' => [
                        'preferred_name' => 'ExchangeRate'
                        , 'type' => 'decimal'
                    ]
                    , 'TRANSDATE' => [
                        'preferred_name' => 'TransactionDate'
                        , 'type' => 'date'
                    ]
                    , 'CLOSED' => [
                        'preferred_name' => 'Closed'
                        , 'type' => 'datetime'
                    ]
                    , 'DUEDATE' => [
                        'preferred_name' => 'DueDate'
                        , 'type' => 'datetime',
                    ]
                    , 'SENTTOSCOMS' => [
                        'preferred_name' => 'SentToSCOMS'
                        , 'type' => 'int'
                    ]
                    , 'COPYOFTXT' => [
                        'preferred_name' => 'SentToSCOMSComments'
                        , 'type' => 'string'
                    ]
                    , 'INVOICE' => [
                        'preferred_name' => 'Invoice'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'Invoice'
                            , 'preferred_local_key_name' => 'InvoiceNumber'
                            , 'remote_field' => 'InvoiceId'
                            , 'remote_type' => 'parent'
                            , 'filter' => 'InvoiceId ne $NULL$'
                            , 'remote_entity' => 'cust_invoice_table'
                        ]
                    ]
                    , 'VOUCHER' => [
                        'preferred_name' => 'VoucherNumber'
                        , 'type' => 'string'
                    ]
                    , 'LASTSETTLEVOUCHER' => [
                        'preferred_name' => 'LastSettlementVoucher'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'LastSettlementVoucher'
                            , 'preferred_local_key_name' => 'LastSettlementVoucherNumber'
                            , 'remote_field' => 'VoucherNumber'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_trans'
                            , 'filter' => 'InvoiceNumber ne $NULL$ and TransactionType eq 8'
                        ]
                    ]
                    , 'PAYMID' => [
                        'preferred_name' => 'PaymentId'
                        , 'type' => 'string',
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string',
                    ]
                    , '_INVOICE_INFORMATION' => [
                        'preferred_name' => 'InvoiceInformation'
                        , 'type' => 'detail'
                        , 'lookup_entity' => 'cust_trans'
                        , 'relationship' => [
                            'local_field' => 'InvoiceNumber'
                            , 'remote_field' => 'InvoiceId'
                            , 'remote_type' => 'parent'
                            , 'filter' => 'TransactionType eq 8'
                        ]
                    ]
                    , '_LINE_TRANSACTIONS' => [
                        'preferred_name' => 'LineTransactions'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'OffsetTransactionId'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'cust_invoice_line_transaction'
                        ]
                    ] 
                    , '_LINE_TRANSACTIONS2' => [
                        'preferred_name' => 'SettlementTransactionBreakdown'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'PaymentTransactionId'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'cust_invoice_line_transaction'
                        ]
                    ] 
                    , '_SETTLEMENTS' => [
                        'preferred_name' => 'Settlements'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'OffsetTransactionId'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'cust_trans'
                            , 'filter' => 'TransactionType eq 15'
                        ]
                    ]      
                    , '_SETTLEMENTS2' => [
                        'preferred_name' => 'Settlements2'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'OffsetTransactionId'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'cust_trans'
                            , 'filter' => 'TransactionType eq 24'
                        ]
                    ]                
                    , '_TAX_TRANSACTIONS' => [
                        'preferred_name' => 'TaxTransactions'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'VoucherNumber'
                            , 'remote_field' => 'VoucherNumber'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'tax_trans'
                        ]
                    ]  
                ]              
            ]
            , 'cust_invoice_table' => [
                'internal_name' => 'CustInvoiceTable'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1,
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                    , 'DUEDATE' => [
                        'preferred_name' => 'DueDate'
                        , 'type' => 'datetime',
                    ]
                    , 'ENDDATE' => [
                        'preferred_name' => 'EndDate'
                        , 'type' => 'datetime',
                    ]
                    , 'POSTED' => [
                        'preferred_name' => 'IsPosted'
                        , 'type' => 'int'
                    ]
                    , 'CURRENCYCODE' => [
                        'preferred_name' => 'CurrencyCode'
                        , 'type' => 'string'
                    ]
                    , 'DESCRIPTION' => [
                        'preferred_name' => 'Description'
                        , 'type' => 'string'
                    ]
                    , 'LEDGERDIMENSION' => [
                        'preferred_name' => 'LedgerDimension'
                        , 'type' => 'bigint'
                    ]
                    , 'INVOICEACCOUNT' => [
                        'preferred_name' => 'InvoiceAccount'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'InvoiceAccount'
                            , 'preferred_local_key_name' => 'InvoiceAccountNumber'
                            , 'remote_field' => 'AccountNumber'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_table'
                        ]
                    ]
                    , 'PAYMENT' => [
                        'preferred_name' => 'PaymentTerms'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'PaymentTerms'
                            , 'preferred_local_key_name' => 'PaymentTermId'
                            , 'remote_field' => 'PaymentTermId'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'paymentterm'
                        ]
                    ]
                    , 'ORDERACCOUNT' => [
                        'preferred_name' => 'OrderAccount'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'OrderAccount'
                            , 'preferred_local_key_name' => 'OrderAccountNumber'
                            , 'remote_field' => 'AccountNumber'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_table'
                        ]
                    ]
                    , 'INVOICEID' => [
                        'preferred_name' => 'InvoiceId'
                        , 'type' => 'string'
                        // , 'relationship' => [
                        //     'local_field' => 'InvoiceInformation'
                        //     , 'preferred_local_key_name' => 'InvoiceNumber'
                        //     , 'remote_field' => 'Invoice'
                        //     , 'filter' => 'InvoiceNumber ne $NULL$ and TransactionType eq 8'
                        //     , 'remote_type' => 'parent'
                        //     , 'remote_entity' => 'cust_trans'
                        // ],
                    ]
                    , 'INVOICEREFERENCE' => [
                        'preferred_name' => 'Reference'
                        , 'type' => 'string'
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string',
                    ]
                    , '_CUSTOMER' => [
                        'preferred_name' => 'Customer'
                        , 'type' => 'detail'
                        , 'lookup_entity' => 'cust_table'
                        , 'relationship' => [
                            'local_field' => 'AccountNumber'
                            , 'remote_field' => 'AccountNumber'
                            , 'remote_type' => 'parent'
                        ],
                    ]
                    , '_LINES' => [
                        'preferred_name' => 'Lines'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'InvoiceId'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'cust_invoice_line'
                        ],
                    ]
                    , '_INVOICEFINANCIALS' => [
                        'preferred_name' => 'InvoiceInformation'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'InvoiceId'
                            , 'preferred_local_key_name' => 'InvoiceInformationId'
                            , 'remote_field' => 'Invoice'
                            , 'filter' => '(InvoiceNumber ne $BLANK$ and TransactionType eq 8)'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_trans'
                        ],
                    ]
                ]
            ]
            , 'dimension_attribute_value_combination' => [
                'internal_name' => 'DimensionAttributeValueCombination'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                    ]
                    , 'ACCOUNTSTRUCTURE' => [
                        'preferred_name' => 'AccountStructure'
                        , 'type' => 'datetime',
                    ]
                    , 'DISPLAYVALUE' => [
                        'preferred_name' => 'DisplayValue'
                        , 'type' => 'datetime',
                    ]
                    , 'LEDGERDIMENSIONTYPE' => [
                        'preferred_name' => 'LedgerDimensionType'
                        , 'type' => 'int',
                    ]
                    , 'MAINACCOUNT' => [
                        'preferred_name' => 'MainAccount'
                        , 'type' => 'bigint'
                        , 'relationship' => [
                            'local_field' => 'MainAccount'
                            , 'preferred_local_key_name' => 'MainAccountId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'main_account'
                        ]
                    ]
                    , '_ACCOUNTING_DISTRIBUTION' => [
                        'preferred_name' => 'AccountingDistribution'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'LedgerDimension'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'accounting_distribution'
                        ]
                    ]
                ]
            ]
            , 'accounting_distribution' => [
                'internal_name' => 'AccountingDistribution'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1,
                    ]
                    , 'LEDGERDIMENSION' => [
                        'preferred_name' => 'LedgerDimension'
                        , 'type' => 'bigint',
                    ]
                    , 'ACCOUNTINGDATE' => [
                        'preferred_name' => 'AccountingDate'
                        , 'type' => 'date',
                    ]
                    , 'MONETARYAMOUNT' => [
                        'preferred_name' => 'MonetaryAmount'
                        , 'type' => 'int',
                    ]
                    , 'TRANSACTIONCURRENCY' => [
                        'preferred_name' => 'TransactionCurrency'
                        , 'type' => 'string'
                    ]
                    , 'SOURCEDOCUMENTLINE' => [
                        'preferred_name' => 'SourceDocumentLine'
                        , 'type' => 'bigint'
                    ]
                ]
            ]
            , 'main_account' => [
                'internal_name' => 'MainAccount'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1,
                    ]
                    , 'MAINACCOUNTID' => [
                        'preferred_name' => 'MainAccount'
                        , 'type' => 'string',
                    ]
                    , 'NAME' => [
                        'preferred_name' => 'Name'
                        , 'type' => 'string',
                    ]
                    , 'TYPE' => [
                        'preferred_name' => 'Type'
                        , 'type' => 'int',
                    ]
                ]
            ]
            , 'cust_invoice_line' => [
                'internal_name' => 'CustInvoiceLine'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1,
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                    , 'INVOICECREATIONDATE' => [
                        'preferred_name' => 'InvoiceCreated'
                        , 'type' => 'datetime',
                    ]     
                    , 'INVOICEDUEDATE' => [
                        'preferred_name' => 'InvoiceDueDate'
                        , 'type' => 'date',
                    ]                
                    , 'PARENTRECID' => [
                        'preferred_name' => 'Invoice'
                        , 'type' => 'int'
                        , 'lookup_entity' => 'cust_invoice_table'
                        , 'relationship' => [
                            'local_field' => 'Invoice'
                            , 'preferred_local_key_name' => 'InvoiceId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                        ],
                    ]
                    , 'SFCUSTOMERPRODUCTID' => [
                        'preferred_name' => 'CustomerProduct'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'CustomerProduct'
                            , 'preferred_local_key_name' => 'CustomerProductId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'customer_product'
                            , 'remote_driver' => 'salesforce'
                        ],
                    ]
                    , 'SFOPPORTUNITYID' => [
                        'preferred_name' => 'Opportunity'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'Opportunity'
                            , 'preferred_local_key_name' => 'OpportunityId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'opportunity'
                            , 'remote_driver' => 'salesforce'
                        ]
                    ]
                    , 'SCOMSLINKINGPENDING' => [
                        'preferred_name' => 'SCOMSRevisitRequired'
                        , 'type' => 'int'
                        , 'mandatory' => 1,
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string',
                    ]
                    , 'LEDGERDIMENSION' => [
                        'preferred_name' => 'LedgerDimension'
                        , 'type' => 'bigint'
                        , 'relationship' => [
                            'local_field' => 'LedgerDimension'
                            , 'preferred_local_key_name' => 'LedgerDimensionId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'dimension_attribute_value_combination'
                        ]
                    ]
                    , 'AMOUNTCUR' => [
                        'preferred_name' => 'Amount'
                        , 'type' => 'decimal',
                    ]
                    , 'AMOUNTDETAILS' => [
                        'preferred_name' => 'AmountDetails'
                        , 'type' => 'string',
                    ]
                    , 'DESCRIPTION' => [
                        'preferred_name' => 'Description'
                        , 'type' => 'string',
                    ]
                    , 'CURRENCYCODE' => [
                        'preferred_name' => 'CurrencyCode'
                        , 'type' => 'string',
                    ]
                    , 'QUANTITY' => [
                        'preferred_name' => 'Quantity'
                        , 'type' => 'int',
                    ]
                    , 'UOM' => [
                        'preferred_name' => 'UnitOfMeasure'
                        , 'type' => 'string',
                    ]
                    , 'INVOICETXT' => [
                        'preferred_name' => 'InvoiceText'
                        , 'type' => 'string',
                    ]
                    , 'CUSTINVOICELINETEMPLATE' => [
                        'preferred_name' => 'Template'
                        , 'type' => 'int'
                        , 'relationship' => [
                            'local_field' => 'Template'
                            , 'preferred_local_key_name' => 'TemplateId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_invoice_standard_line_template'
                        ]
                    ]
                    , '_TRANSACTIONS' => [
                        'preferred_name' => 'Transactions'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'InvoiceLineId'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'cust_invoice_line_transaction'
                        ]
                    ]
                    , '_BLANKCOTEMPLATERS' => [
                        'preferred_name' => 'BlankCoTemplaters'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'TemplateId'
                            , 'remote_field' => 'TemplateId'
                            , 'remote_type' => 'child'
                            , 'remote_entity' => 'cust_invoice_line'
                            , 'filter' => 'SCOMSRevisitRequired gt 0'
                        ]
                    ]
                ]
            ]
            , 'cust_invoice_standard_line_template' => [
                'internal_name' => 'CustInvoiceStandardLineTemplate'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1,
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                    , 'SFCUSTOMERPRODUCTID' => [
                        'preferred_name' => 'CustomerProduct'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'CustomerProduct'
                            , 'preferred_local_key_name' => 'CustomerProductId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'customer_product'
                            , 'remote_driver' => 'salesforce'
                        ],
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string',
                    ]
                ]
            ]
            , 'cust_invoice_line_transaction' => [
                'internal_name' => 'CustInvoiceLineTrans'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1,
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                    , 'INVOICELINEID' => [
                        'preferred_name' => 'InvoiceLine'
                        , 'type' => 'int'
                        , 'relationship' => [
                            'local_field' => 'InvoiceLine'
                            , 'preferred_local_key_name' => 'InvoiceLineId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_invoice_line'
                        ]
                    ]
                    , 'OFFSETTRANSACTIONID' => [
                        'preferred_name' => 'OffsetTransaction'
                        , 'type' => 'int'
                        , 'relationship' => [
                            'local_field' => 'OffsetTransaction'
                            , 'preferred_local_key_name' => 'OffsetTransactionId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_trans'
                        ]
                    ]
                    , 'PAYMENTTRANSACTIONID' => [
                        'preferred_name' => 'PaymentTransaction'
                        , 'type' => 'int'
                        , 'relationship' => [
                            'local_field' => 'PaymentTransaction'
                            , 'preferred_local_key_name' => 'PaymentTransactionId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_trans'
                        ]
                    ]
                    , 'INVOICEID' => [
                        'preferred_name' => 'Invoice'
                        , 'type' => 'int'
                        , 'relationship' => [
                            'local_field' => 'Invoice'
                            , 'preferred_local_key_name' => 'InvoiceId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cust_invoice_table'
                        ]
                    ]
                    , 'UNIQUELINEID' => [
                        'preferred_name' => 'UniqueLineId'
                        , 'type' => 'string'
                    ]
                    , 'SENTTOSCOMS' => [
                        'preferred_name' => 'SentToSCOMS'
                        , 'type' => 'int'
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string',
                    ]
                    , 'CURRENCYCODE' => [
                        'preferred_name' => 'CurrencyCode'
                        , 'type' => 'string',
                    ]
                    , 'AMOUNT' => [
                        'preferred_name' => 'Amount'
                        , 'type' => 'decimal',
                    ]
                    , 'NAME' => [
                        'preferred_name' => 'Name'
                        , 'type' => 'string',
                    ]
                    , 'ACCOUNT' => [
                        'preferred_name' => 'Account'
                        , 'type' => 'string',
                    ]
                    , 'PAYABLECOMMISSION' => [
                        'preferred_name' => 'PayableCommission'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'PayableCommission'
                            , 'preferred_local_key_name' => 'PayableCommissionId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'payable_commission'
                            , 'remote_driver' => 'salesforce'
                        ]
                    ]
                    , 'ACCOUNTMANAGER' => [
                        'preferred_name' => 'AccountManager'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'AccountManager'
                            , 'preferred_local_key_name' => 'AccountManagerId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'user'
                            , 'remote_driver' => 'salesforce'
                        ]
                    ]
                    , 'ACCOUNTMANAGEREXTENSION' => [
                        'preferred_name' => 'AccountManagerExtension'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'AccountManagerExtension'
                            , 'preferred_local_key_name' => 'AccountManagerExtensionId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'user_extension'
                            , 'remote_driver' => 'salesforce'
                        ]
                    ]
                    , 'CUSTOMERPRODUCT' => [
                        'preferred_name' => 'CustomerProduct'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'CustomerProduct'
                            , 'preferred_local_key_name' => 'CustomerProductId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'customer_product'
                            , 'remote_driver' => 'salesforce'
                        ]
                    ]
                    , 'OPPORTUNITY' => [
                        'preferred_name' => 'Opportunity'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'Opportunity'
                            , 'preferred_local_key_name' => 'OpportunityId'
                            , 'remote_field' => 'Id'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'opportunity'
                            , 'remote_driver' => 'salesforce'
                        ]
                    ]
                    , 'INFLOWTYPE' => [
                        'preferred_name' => 'InflowType'
                        , 'type' => 'string',
                    ]
                    , 'NARRATIVE' => [
                        'preferred_name' => 'Narrative'
                        , 'type' => 'string'
                        , 'type_description' => 'max'
                    ]
                    , 'INVOICENUMBER' => [
                        'preferred_name' => 'InvoiceNumber'
                        , 'type' => 'string',
                    ]
                    , 'CONVERSIONRATE' => [
                        'preferred_name' => 'ConversionRate'
                        , 'type' => 'decimal'
                        , 'type_description' => '14,4'
                    ]
                    , 'EXCHANGERATE' => [
                        'preferred_name' => 'ExchangeRate'
                        , 'type' => 'decimal'
                        , 'type_description' => '14,4'
                    ]
                    , 'VALUEDATE' => [
                        'preferred_name' => 'ValueDate'
                        , 'type' => 'date',
                    ]
                    , 'DUEDATE' => [
                        'preferred_name' => 'DueDate'
                        , 'type' => 'date',
                    ]
                    , '_INFLOW' => [
                        'preferred_name' => 'Inflow'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'TransactionLineId'
                            , 'remote_type' => 'parent'
                            , 'remote_entity' => 'cash_inflow'
                            , 'remote_driver' => 'salesforce'
                        ]
                    ]
                ]
            ]
            , 'purchased_item_reference' => [
                'internal_name' => 'MONE_PurchLine'
                , 'description' => 'A table'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string'
                    ]
                    , 'PURCHPARMLINERECID' => [
                        'preferred_name' => 'PurchParmLineRecId'
                        , 'type' => 'string'
                    ]
                    , 'SENTTOREMEDY' => [
                        'preferred_name' => 'SentToRemedy'
                        , 'type' => 'string'
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                ]
            ]
            , 'invent_trans' => [
                'internal_name' => 'InventTrans'
                , 'description' => 'A table'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string'
                    ]
                    , 'ITEMID' => [
                        'preferred_name' => 'ItemId'
                        , 'type' => 'string'
                    ]
                    , 'SENTTOREMEDY' => [
                        'preferred_name' => 'SentToRemedy'
                        , 'type' => 'int'
                    ]
                    , 'QTY' => [
                        'preferred_name' => 'Quantity'
                        , 'type' => 'int'
                    ]
                    , 'INVENTDIMID' => [
                        'preferred_name' => 'InventDimId'
                        , 'type' => 'string'
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                ]
            ]
            , 'invent_table' => [
                'internal_name' => 'InventTable'
                , 'description' => 'A table'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string'
                    ]
                    , 'ITEMID' => [
                        'preferred_name' => 'ItemId'
                        , 'type' => 'string'
                    ]
                    , 'NAMEALIAS' => [
                        'preferred_name' => 'Name'
                        , 'type' => 'int'
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                ]
            ]
            , 'invent_sum' => [
                'internal_name' => 'InventSum'
                , 'description' => 'A table'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string'
                    ]
                    , 'ITEMID' => [
                        'preferred_name' => 'ItemId'
                        , 'type' => 'string'
                    ]
                    , 'ITEMGROUPID' => [
                        'preferred_name' => 'ItemGroupId'
                        , 'type' => 'int'
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                ]
            ]
            , 'invent_dim' => [
                'internal_name' => 'InventDim'
                , 'description' => 'A table'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string'
                    ]
                    , 'INVENTDIMID' => [
                        'preferred_name' => 'InventDimId'
                        , 'type' => 'string'
                    ]
                    , 'INVENTBATCHID' => [
                        'preferred_name' => 'BatchId'
                        , 'type' => 'string'
                    ]
                    , 'INVENTLOCATIONID' => [
                        'preferred_name' => 'WarehouseId'
                        , 'type' => 'string'
                    ]
                    , 'WMSLOCATIONID' => [
                        'preferred_name' => 'LocationId'
                        , 'type' => 'string'
                    ]
                    , 'WMSPALLETID' => [
                        'preferred_name' => 'PalletId'
                        , 'type' => 'string'
                    ]
                    , 'INVENTSITEID' => [
                        'preferred_name' => 'SiteId'
                        , 'type' => 'string'
                    ]
                    , 'INVENTSIZEID' => [
                        'preferred_name' => 'SizeId'
                        , 'type' => 'string'
                    ]
                    , 'INVENTSERIALID' => [
                        'preferred_name' => 'SerialId'
                        , 'type' => 'string'
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                ]
            ]
            , 'tax_trans' => [
                'internal_name' => 'TaxTrans'
                , 'description' => 'A table'
                , 'fields' => [
                    'RECID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'int'
                        , 'mandatory' => 1
                    ]
                    , 'DATAAREAID' => [
                        'preferred_name' => 'DataArea'
                        , 'type' => 'string'
                    ]
                    , 'INVOICEID' => [
                        'preferred_name' => 'InvoiceId'
                        , 'type' => 'string'
                    ]
                    , 'CURRENCYCODE' => [
                        'preferred_name' => 'CurrencyCode'
                        , 'type' => 'string'
                    ]
                    , 'TAXAMOUNTCUR' => [
                        'preferred_name' => 'Amount'
                        , 'type' => 'int'
                    ]
                    , 'TAXBASEAMOUNTCUR' => [
                        'preferred_name' => 'BaseAmount'
                        , 'type' => 'int'
                    ]
                    , 'VOUCHER' => [
                        'preferred_name' => 'VoucherNumber'
                        , 'type' => 'string'
                    ]
                    , 'MODIFIEDDATETIME' => [
                        'preferred_name' => 'Modified'
                        , 'type' => 'datetime',
                    ]
                    , 'CREATEDDATETIME' => [
                        'preferred_name' => 'Created'
                        , 'type' => 'datetime',
                    ]
                ]
            ]
        ]];

        $in_store['d365']['account'] = $in_store['d365']['rootaccount'];

        variable_set('D365_DRIVER_OBJECTS', $in_store);
    }    

    return $in_store;
}
