<?php

module_load_include('module', 'settings_provider');
$module_path = drupal_get_path('module', 'd365_connection_driver');
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/forms/admin.inc');
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/D365ConnectionDriver.php');

use com\mainone\middleware\D365ConnectionDriver;

/**
 * Implements hook_permission
 * @return array
 */
function d365_connection_driver_permission()
{
    $permission = [];
    return $permission;
}

function d365_connection_driver_connection_driver_d365_alter(&$container)
{
    $connection_settings = d365_connection_driver__get_settings();
    $driver = new D365ConnectionDriver(function ($x) {
        return mware_connection_driver__get_driver($x);
    }, function () {
    }, 'd365', $connection_settings);

    $defs = d365_connection_driver__get_entity_definitions_local();
    $driver->setEntities(($defs));
    $driver->addUtilityFunction('date_sync_util', function(){
            $args = func_get_args();
            $return = module_invoke('settings_provider', '_update_cache', ...$args);
    });
    $container['d365'] = $driver;
}

function d365_connection_driver__user_access($args)
{
    return true;
}

/**
 * Returns the connection settings with which to connect to d365.
 * @return \stdClass
 */
function d365_connection_driver__get_settings($settings = 'default')
{
    $d365_settings = variable_get('d365_settings', [
        'authentication_url' => ''
        , 'resource' => ''
        , 'grant_type' => ''
        , 'client_id' => ''
        , 'client_secret' => ''
    ]);

    return $d365_settings;
}

/**
 * Returns entity definitions that have been marked as cacheable to the specified entity.
 *
 * @param String $targetDriver the connection driver to use to retrieve the cache.
 * @return void
 */
function d365_connection_driver__get_cached_entity_definitions($targetDriver)
{
    return settings_provider__format_cached_definition('d365', $targetDriver, function(){
        $args = func_get_args();
        $return = d365_connection_driver__get_entity_definitions_local(...$args);
        return $return;
    });
}

function d365_connection_driver__get_entity_definitions_local(){
    return d365_connection_driver__get_entity_definitions(...func_get_args())['d365'];
}

/**
 * Returns the full definition of an entity or the definition of the specified component.
 * Components include: fields, internal_name
 * @param string $entity_name
 * @param string $component
 * @return array
 */
function d365_connection_driver__get_entity_definitions()
{
    // $in_store = variable_get('D365_DRIVER_OBJECTS');

    // if(!is_null($in_store)){      

        $in_store = ['d365'=> [
            'customer' => [
                'internal_name' => 'Customers'
                // , 'cache_to' => 'sql'
                // , 'cache_freq' => 60
                // , 'cache_duplicate_check_query' => 'BusinessEntityId eq \'{}->BusinessEntityId\' and AccountNumber eq \'{}->AccountNumber\''
                // , 'cache_duplicate_check_select' => 'AccountNumber'
                , 'fields' => [
                    '_Id' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'formula'
                        , 'formula' => 'strtoupper(\'{BusinessEntityId}\').\'-\'.\'{AccountNumber}\''
                        , 'formula_type' => 'string'
                        , 'mandatory' => 1,
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , 'Name' => [
                        'preferred_name' => 'Name'
                        , 'type' => 'string'
                    ]
                    // , 'ModifiedOn' => [
                    //     'preferred_name' => 'Modified'
                    //     , 'type' => 'datetime'
                    // ]
                    // , 'CreateDateTime' => [
                    //     'preferred_name' => 'Created'
                    //     , 'type' => 'datetime'
                    // ]
                    , 'CustomerAccount' => [
                        'preferred_name' => 'AccountNumber'
                        , 'type' => 'string'
                    ]
                    , 'PartyType' => [
                        'preferred_name' => 'PartyType'
                        , 'type' => 'string'
                    ]
                    , 'PrimaryContactEmail' => [
                        'preferred_name' => 'PrimaryContactEmail'
                        , 'type' => 'string'
                    ]
                    , 'PrimaryContactPhone' => [
                        'preferred_name' => 'PrimaryContactPhoneNumber'
                        , 'type' => 'string'
                    ]
                    , 'PrimaryContactEmailDescription' => [
                        'preferred_name' => 'PrimaryContactEmailDescription'
                        , 'type' => 'string'
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , '_Invoices' => [
                        'preferred_name' => 'Invoices'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'AccountNumber'
                            , 'remote_field' => 'InvoiceAccount'
                            , 'remote_entity' => 'freetext_invoice'
                            , 'remote_type' => 'child'
                        ]
                    ]
                    , '_PostedInvoices' => [
                        'preferred_name' => 'PostedInvoices'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'AccountNumber'
                            , 'remote_field' => 'InvoiceAccount'
                            , 'remote_entity' => 'freetext_invoice'
                            , 'remote_type' => 'child'
                            , 'filter' => "InvoiceNumber ne 'Not posted'"
                        ]
                    ]
                    , '_UnpostedInvoices' => [
                        'preferred_name' => 'UnpostedInvoices'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'AccountNumber'
                            , 'remote_field' => 'InvoiceAccount'
                            , 'remote_entity' => 'freetext_invoice'
                            , 'remote_type' => 'child'
                            , 'filter' => "InvoiceNumber eq 'Not posted'"
                        ]
                    ]
                    , '_DictionaryInfo' => [
                        'preferred_name' => 'DictionaryInfo'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'AccountNumber'
                            , 'remote_field' => 'SystemKey'
                            , 'remote_entity' => 'customerinfo'
                            , 'remote_type' => 'parent'
                            , 'remote_driver' => 'sql'
                            , 'filter' => "SystemName eq 'd365'"
                        ]
                    ]
                ]
            ]
            , 'sales_invoice' => [
                'internal_name' => 'SalesInvoiceHeaders'
                , 'fields' => [
                    '_ID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'formula'
                        , 'formula' => '\'{CustomerAccount}\'. \':::\'. \'{InvoiceNumber}\''
                        , 'formula_type' => 'string'
                        , 'mandatory' => 1,
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceNumber' => [
                        'preferred_name' => 'InvoiceNumber'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceDate' => [
                        'preferred_name' => 'DueDate'
                        , 'type' => 'datetime',
                    ]
                    , 'InvoiceAddressCountryRegionId' => [
                        'preferred_name' => 'InvoiceAddressCountryRegion'
                        , 'type' => 'string',
                    ]
                    , 'CurrencyCode' => [
                        'preferred_name' => 'CurrencyCode'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceCustomerAccountNumber' => [
                        'preferred_name' => 'CustomerAccount'
                        , 'type' => 'string',
                    ]
                    , 'ContactPersonId' => [
                        'preferred_name' => 'ContactPerson'
                        , 'type' => 'string',
                    ]
                    , 'DeliveryTermsCode' => [
                        'preferred_name' => 'DeliveryTermsCode'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceHeaderTaxAmount' => [
                        'preferred_name' => 'TaxAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'SalesOrderNumber' => [
                        'preferred_name' => 'SalesOrderNumber'
                        , 'type' => 'string',
                    ]
                    , 'CustomersOrderReference' => [
                        'preferred_name' => 'Reference'
                        , 'type' => 'string',
                    ]
                    , 'SalesOrderResponsiblePersonnelNumber' => [
                        'preferred_name' => 'SalesOrderResponsiblePersonnelNumber'
                        , 'type' => 'string',
                    ]
                    , 'TotalInvoiceAmount' => [
                        'preferred_name' => 'Amount'
                        , 'type' => 'decimal',
                    ]
                    , 'TotalDiscountAmount' => [
                        'preferred_name' => 'DiscountAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'InvoiceAddressStreet' => [
                        'preferred_name' => 'InvoiceAddressStreet'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceAddressZipCode' => [
                        'preferred_name' => 'InvoiceAddressZipCode'
                        , 'type' => 'string',
                    ]
                    , 'TotalDiscountCustomerGroupCode' => [
                        'preferred_name' => 'TotalDiscountCustomerGroupCode'
                        , 'type' => 'int',
                    ]
                    , 'DeliveryModeCode' => [
                        'preferred_name' => 'DeliveryModeCode'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceAddressCity' => [
                        'preferred_name' => 'InvoiceAddressCity'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceAddressCountryRegionISOCode' => [
                        'preferred_name' => 'InvoiceAddressCountryRegionISOCode'
                        , 'type' => 'string',
                    ]
                    , 'TotalTaxAmount' => [
                        'preferred_name' => 'TotalTaxAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'InvoiceAddressStreetNumber' => [
                        'preferred_name' => 'InvoiceAddressStreetNumber'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceAddressState' => [
                        'preferred_name' => 'InvoiceAddressState'
                        , 'type' => 'string',
                    ]
                    , 'PaymentTermsName' => [
                        'preferred_name' => 'PaymentTerms'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'PaymentTerms'
                            , 'preferred_local_key_name' => 'PaymentTermsId'
                            , 'remote_field' => 'Name'
                            , 'remote_entity' => 'payment_term'
                            , 'remote_type' => 'parent'
                        ]
                    ]
                    , '_Lines' => [
                        'preferred_name' => 'Lines'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'InvoiceNumber'
                            , 'remote_field' => 'InvoiceNumber'
                            , 'remote_entity' => 'sales_invoice_line'
                            , 'remote_type' => 'child'
                        ]
                    ]
                ]
            ]
            , 'sales_invoice_line' => [
                'internal_name' => 'SalesInvoiceLines'
                , 'fields' => [
                    '_ID' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'formula'
                        , 'formula' => '\'{InvoiceNumber}\'. \':::\'. \'{LineCreationSequenceNumber}\''
                        , 'formula_type' => 'string'
                        , 'mandatory' => 1,
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceNumber' => [
                        'preferred_name' => 'Invoice'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'Invoice'
                            , 'preferred_local_key_name' => 'InvoiceNumber'
                            , 'remote_field' => 'InvoiceNumber'
                            , 'remote_entity' => 'sales_invoice'
                            , 'remote_type' => 'parent'
                        ]
                    ]
                    , 'InvoiceDate' => [
                        'preferred_name' => 'InvoiceDate'
                        , 'type' => 'datetime',
                    ]
                    , 'LineCreationSequenceNumber' => [
                        'preferred_name' => 'LineCreationSequenceNumber'
                        , 'type' => 'int',
                    ]
                    , 'CurrencyCode' => [
                        'preferred_name' => 'CurrencyCode'
                        , 'type' => 'string',
                    ]
                    , 'InvoicedQuantity' => [
                        'preferred_name' => 'Quantity'
                        , 'type' => 'decimal',
                    ]
                    , 'LineTotalDiscountAmount' => [
                        'preferred_name' => 'DiscountAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'ProductDescription' => [
                        'preferred_name' => 'ProductDescription'
                        , 'type' => 'string',
                    ]
                    , 'LineTotalTaxAmount' => [
                        'preferred_name' => 'TaxAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'ProductName' => [
                        'preferred_name' => 'ProductName'
                        , 'type' => 'string',
                    ]
                    , 'LineTotalChargeAmount' => [
                        'preferred_name' => 'ChargeAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'SalesUnitSymbol' => [
                        'preferred_name' => 'UnitOfMeasure'
                        , 'type' => 'string',
                    ]
                    , 'ConfirmedShippingDate' => [
                        'preferred_name' => 'ConfirmedShippingDate'
                        , 'type' => 'datetime',
                    ]
                    , 'ProductNumber' => [
                        'preferred_name' => 'ProductNumber'
                        , 'type' => 'string',
                    ]
                    , 'SalesPrice' => [
                        'preferred_name' => 'SalesPrice'
                        , 'type' => 'decimal',
                    ]
                    , 'LineAmount' => [
                        'preferred_name' => 'Amount'
                        , 'type' => 'string',
                    ]
                ]
            ]
            , 'freetext_invoice' => [
                'internal_name' => 'FreeTextInvoiceHeaders'
                , 'fields' => [
                    'InvoiceIdentifier' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'bigint'
                        , 'mandatory' => 1,
                    ]
                    , 'InvoiceDate' => [
                        'preferred_name' => 'InvoiceDate'
                        , 'type' => 'datetime',
                    ]
                    , 'DueDate' => [
                        'preferred_name' => 'DueDate'
                        , 'type' => 'date',
                    ]
                    , 'DocumentDate' => [
                        'preferred_name' => 'DocumentDate'
                        , 'type' => 'datetime',
                    ]
                    , 'IsCorrection' => [
                        'preferred_name' => 'IsCorrection'
                        , 'type' => 'string'
                    ]
                    , 'ExchangeRate' => [
                        'preferred_name' => 'ExchangeRate'
                        , 'type' => 'decimal'
                    ]
                    , 'FreeTextNumber' => [
                        'preferred_name' => 'InvoiceNumber'
                        , 'type' => 'string'
                    ]
                    , 'InvoiceAccount' => [
                        'preferred_name' => 'InvoiceAccount'
                        , 'type' => 'string'
                    ]
                    , 'CustomerAccount' => [
                        'preferred_name' => 'CustomerAccount'
                        , 'type' => 'string'
                    ]
                    , 'CorrectionType' => [
                        'preferred_name' => 'CorrectionType'
                        , 'type' => 'string'
                    ]
                    , 'CurrencyCode' => [
                        'preferred_name' => 'CurrencyCode'
                        , 'type' => 'string'
                    ]
                    , 'CustomerReference' => [
                        'preferred_name' => 'CustomerReference'
                        , 'type' => 'string'
                    ]
                    , 'IsPosted' => [
                        'preferred_name' => 'IsPosted'
                        , 'type' => 'boolean'
                    ]
                    , 'CustomerGroup' => [
                        'preferred_name' => 'CustomerGroup'
                        , 'type' => 'string'
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , 'BankAccountId' => [
                        'preferred_name' => 'BankAccount'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'BankAccount'
                            , 'preferred_local_key_name' => 'BankAccountId'
                            , 'remote_field' => 'CompanyBankAccountId'
                            , 'remote_entity' => 'bank_account'
                            , 'remote_type' => 'parent'
                        ]
                    ]
                    , 'TermsOfPayment' => [
                        'preferred_name' => 'PaymentTerms'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'PaymentTerms'
                            , 'preferred_local_key_name' => 'PaymentTermsId'
                            , 'remote_field' => 'Name'
                            , 'remote_entity' => 'payment_term'
                            , 'remote_type' => 'parent'
                        ]
                    ]
                    , '_CustomerId' => [
                        'preferred_name' => 'CustomerId'
                        , 'type' => 'formula'
                        , 'formula' => 'strtoupper(\'{BusinessEntityId}\').\'-\'.\'{InvoiceAccount}\''
                        , 'formula_type' => 'string'
                    ]
                    , '_Lines' => [
                        'preferred_name' => 'Lines'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'Id'
                            , 'remote_field' => 'InvoiceId'
                            , 'remote_entity' => 'freetext_invoice_line'
                            , 'remote_type' => 'child'
                        ]
                    ]
                ]
            ]
            , 'freetext_invoice_line' => [
                'internal_name' => 'FreeTextInvoiceLines'
                , 'fields' => [
                    '_Id' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'formula'
                        , 'formula' => 'strtoupper(\'{BusinessEntityId}\').\'-\'.\'{InvoiceId}\''
                        , 'formula_type' => 'string'
                        , 'mandatory' => 1,
                    ]
                    , 'ParentRecId' => [
                        'preferred_name' => 'RelatedInvoice'
                        , 'type' => 'bigint'
                        , 'relationship' => [
                            'local_field' => 'RelatedInvoice'
                            , 'preferred_local_key_name' => 'InvoiceId'
                            , 'remote_field' => 'Id'
                            , 'remote_entity' => 'freetext_invoice_line'
                            , 'remote_type' => 'parent'
                        ]
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , 'Description' => [
                        'preferred_name' => 'Description'
                        , 'type' => 'string',
                    ]
                    , 'LineNumber' => [
                        'preferred_name' => 'LineNumber'
                        , 'type' => 'int',
                    ]
                    , 'Quantity' => [
                        'preferred_name' => 'Quantity'
                        , 'type' => 'decimal',
                    ]
                    , 'InvoiceText' => [
                        'preferred_name' => 'InvoiceText'
                        , 'type' => 'string',
                    ]
                    , 'SalesUnit' => [
                        'preferred_name' => 'UnitOfMeasure'
                        , 'type' => 'string',
                    ]
                    , 'AmountDetails' => [
                        'preferred_name' => 'AmountDetails'
                        , 'type' => 'string',
                    ]
                    , 'TransactionCurrencyAmount' => [
                        'preferred_name' => 'Amount'
                        , 'type' => 'decimal',
                    ]
                ]
            ]
            , 'general_ledger_cust_invoice_journal_headers' => [
                'internal_name' => 'GeneralLedgerCustInvoiceJournalHeaders'
                , 'fields' => [
                    '_Id' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'formula'
                        , 'formula' => 'strtoupper(\'{BusinessEntityId}\').\'-\'.\'{JournalBatchNumber}\''
                        , 'formula_type' => 'string'
                        , 'mandatory' => 1,
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , 'JournalBatchNumber' => [
                        'preferred_name' => 'JournalBatchNumber'
                        , 'type' => 'string',
                    ]
                    , 'JournalName' => [
                        'preferred_name' => 'JournalName'
                        , 'type' => 'string',
                    ]
                    , 'Description' => [
                        'preferred_name' => 'Description'
                        , 'type' => 'string',
                    ]
                    , 'IsPosted' => [
                        'preferred_name' => 'IsPosted'
                        , 'type' => 'boolean',
                    ]
                    , '_Lines' => [
                        'preferred_name' => 'Lines'
                        , 'type' => 'detail'
                        , 'relationship' => [
                            'local_field' => 'JournalBatchNumber'
                            , 'remote_field' => 'JournalBatchNumber'
                            , 'remote_entity' => 'general_ledger_cust_invoice_journal_lines'
                            , 'remote_type' => 'child'
                        ]
                    ]
                ]
            ]
            , 'general_ledger_cust_invoice_journal_lines' => [
                'internal_name' => 'GeneralLedgerCustInvoiceJournalLines'
                , 'fields' => [
                    '_Id' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'formula'
                        , 'formula' => 'strtoupper(\'{BusinessEntityId}\').\'-\'.\'{InvoiceNumber}\''
                        , 'formula_type' => 'string'
                        , 'mandatory' => 1,
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , 'JournalBatchNumber' => [
                        'preferred_name' => 'JournalBatchNumber'
                        , 'type' => 'string',
                    ]
                    , 'LineNumber' => [
                        'preferred_name' => 'LineNumber'
                        , 'type' => 'int',
                    ]
                    , 'CreditAmount' => [
                        'preferred_name' => 'CreditAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'OffsetAccountType' => [
                        'preferred_name' => 'OffsetAccountType'
                        , 'type' => 'string',
                    ]
                    , 'ReasonCode' => [
                        'preferred_name' => 'ReasonCode'
                        , 'type' => 'string',
                    ]
                    , 'CashDiscountDate' => [
                        'preferred_name' => 'CashDiscountDate'
                        , 'type' => 'datetime',
                    ]
                    , 'ItemSalesTaxGroup' => [
                        'preferred_name' => 'ItemSalesTaxGroup'
                        , 'type' => 'string',
                    ]
                    , 'Currency' => [
                        'preferred_name' => 'Currency'
                        , 'type' => 'string',
                    ]
                    , 'OffsetTransactionText' => [
                        'preferred_name' => 'OffsetTransactionText'
                        , 'type' => 'string',
                    ]
                    , 'MethodOfPayment' => [
                        'preferred_name' => 'MethodOfPayment'
                        , 'type' => 'string',
                    ]
                    , 'TransactionText' => [
                        'preferred_name' => 'TransactionText'
                        , 'type' => 'string',
                    ]
                    , 'Company' => [
                        'preferred_name' => 'Company'
                        , 'type' => 'string',
                    ]
                    , 'Listcode' => [
                        'preferred_name' => 'ListCode'
                        , 'type' => 'string',
                    ]
                    , 'TransactionType' => [
                        'preferred_name' => 'TransactionType'
                        , 'type' => 'string',
                    ]
                    , 'OffsetAccountDisplayValue' => [
                        'preferred_name' => 'OffsetAccountDisplayValue'
                        , 'type' => 'string',
                    ]
                    , 'DocumentDate' => [
                        'preferred_name' => 'DocumentDate'
                        , 'type' => 'datetime',
                    ]
                    , 'CashDiscountCode' => [
                        'preferred_name' => 'CashDiscountCode'
                        , 'type' => 'string',
                    ]
                    , 'IsWithholdingCalculationEnabled' => [
                        'preferred_name' => 'IsWithholdingCalculationEnabled'
                        , 'type' => 'string',
                    ]
                    , 'DeliveryDate' => [
                        'preferred_name' => 'DeliveryDate'
                        , 'type' => 'datetime',
                    ]
                    , 'OffsetCompany' => [
                        'preferred_name' => 'OffsetCompany'
                        , 'type' => 'string',
                    ]
                    , 'CustomerAccountDisplayValue' => [
                        'preferred_name' => 'CustomerAccountDisplayValue'
                        , 'type' => 'string',
                    ]
                    , 'DocumentNumber' => [
                        'preferred_name' => 'DocumentNumber'
                        , 'type' => 'string',
                    ]
                    , 'DebitAmount' => [
                        'preferred_name' => 'DebitAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'PostingProfile' => [
                        'preferred_name' => 'PostingProfile'
                        , 'type' => 'string',
                    ]
                    , 'ItemWithholdingTaxGroupCode' => [
                        'preferred_name' => 'ItemWithholdingTaxGroupCode'
                        , 'type' => 'string',
                    ]
                    , 'Voucher' => [
                        'preferred_name' => 'Voucher'
                        , 'type' => 'string',
                    ]
                    , 'DueDate' => [
                        'preferred_name' => 'DueDate'
                        , 'type' => 'datetime',
                    ]
                    , 'CashDiscountAmount' => [
                        'preferred_name' => 'CashDiscountAmount'
                        , 'type' => 'decimal',
                    ]
                    , 'Approved' => [
                        'preferred_name' => 'Approved'
                        , 'type' => 'boolean',
                    ]
                    , 'AccountType' => [
                        'preferred_name' => 'AccountType'
                        , 'type' => 'string',
                    ]
                    , 'TypeOfOperation' => [
                        'preferred_name' => 'TypeOfOperation'
                        , 'type' => 'string',
                    ]
                    , 'InvoiceDate' => [
                        'preferred_name' => 'InvoiceDate'
                        , 'type' => 'datetime',
                    ]
                    , 'InvoiceId' => [
                        'preferred_name' => 'InvoiceNumber'
                        , 'type' => 'string',
                    ]
                    , 'DefaultDimensionDisplayValue' => [
                        'preferred_name' => 'DefaultDimensionDisplayValue'
                        , 'type' => 'string',
                    ]
                    , 'TermsOfPayment' => [
                        'preferred_name' => 'PaymentTerms'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'PaymentTerms'
                            , 'preferred_local_key_name' => 'PaymentTermsId'
                            , 'remote_field' => 'Name'
                            , 'remote_entity' => 'payment_term'
                            , 'remote_type' => 'parent'
                        ]
                    ]
                ]
            ]
            , 'payment_term' => [
                'internal_name' => 'PaymentTerms'
                , 'fields' => [
                    '_Id' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'formula'
                        , 'formula' => 'strtoupper(\'{BusinessEntityId}\').\'-\'.\'{Name}\''
                        , 'formula_type' => 'string'
                        , 'mandatory' => 1,
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , 'Name' => [
                        'preferred_name' => 'Name'
                        , 'type' => 'string'
                    ]
                    , 'PaymentScheduleName' => [
                        'preferred_name' => 'PaymentScheduleName'
                        , 'type' => 'string'
                    ]
                    , 'CutoffDayOfMonth' => [
                        'preferred_name' => 'CutoffDayOfMonth'
                        , 'type' => 'int'
                    ]     
                    , 'CreditCardPaymentType' => [
                        'preferred_name' => 'CreditCardPaymentType'
                        , 'type' => 'string'
                    ]
                    , 'PaymentMethodType' => [
                        'preferred_name' => 'PaymentMethodType'
                        , 'type' => 'string'
                    ]
                    , 'PaymentDayName' => [
                        'preferred_name' => 'PaymentDayName'
                        , 'type' => 'string'
                    ]
                    , 'IsDefaultPaymentTerm' => [
                        'preferred_name' => 'IsDefaultPaymentTerm'
                        , 'type' => 'string'
                    ]
                    , 'Description' => [
                        'preferred_name' => 'Description'
                        , 'type' => 'string'
                    ]
                    , 'AdditionalMonthsForCutoffDate' => [
                        'preferred_name' => 'AdditionalMonthsForCutoffDate'
                        , 'type' => 'int'
                    ]     
                    , 'CashPaymentMainAccountIdDisplayValue' => [
                        'preferred_name' => 'CashPaymentMainAccountIdDisplayValue'
                        , 'type' => 'string'
                    ]
                    , 'IsCashPayment' => [
                        'preferred_name' => 'IsCashPayment'
                        , 'type' => 'string'
                    ]
                    , 'PostOffsettingAR' => [
                        'preferred_name' => 'PostOffsettingAR'
                        , 'type' => 'string'
                    ]
                    , 'VendorDueDateUpdatePolicy' => [
                        'preferred_name' => 'VendorDueDateUpdatePolicy'
                        , 'type' => 'string'
                    ]
                    , 'NumberOfMonths' => [
                        'preferred_name' => 'NumberOfMonths'
                        , 'type' => 'int'
                    ]     
                    , 'IsCertifiedCompanyCheck' => [
                        'preferred_name' => 'IsCertifiedCompanyCheck'
                        , 'type' => 'string'
                    ]
                    , 'CreditCardCreditCheckType' => [
                        'preferred_name' => 'CreditCardCreditCheckType'
                        , 'type' => 'string'
                    ]
                    , 'CustomerDueDateUpdatePolicy' => [
                        'preferred_name' => 'CustomerDueDateUpdatePolicy'
                        , 'type' => 'string'
                    ]    
                    , 'NumberOfDays' => [
                        'preferred_name' => 'NumberOfDays'
                        , 'type' => 'int'
                    ]     
                ]
            ]
            , 'bank_account' => [
                'internal_name' => 'BankAccounts'
                , 'fields' => [
                    '_Id' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'formula'
                        , 'formula' => 'strtoupper(\'{BusinessEntityId}\').\'-\'.\'{BankAccountId}\''
                        , 'formula_type' => 'string'
                        , 'mandatory' => 1,
                    ]
                    , 'dataAreaId' => [
                        'preferred_name' => 'BusinessEntityId'
                        , 'type' => 'string',
                    ]
                    , 'BankAccountId' => [
                        'preferred_name' => 'BankAccountId'
                        , 'type' => 'string'
                    ]
                    , 'PositivePayFormatName' => [
                        'preferred_name' => 'PositivePayFormatName'
                        , 'type' => 'string'
                    ]
                    , 'CustomerPaymentFeeMainAccountIdDisplayValue' => [
                        'preferred_name' => 'CustomerPaymentFeeMainAccountIdDisplayValue'
                        , 'type' => 'boolean'
                    ]
                    , 'ActiveFrom' => [
                        'preferred_name' => 'ActiveFrom'
                        , 'type' => 'datetime'
                    ]
                    , 'DiscountInterestsFee' => [
                        'preferred_name' => 'DiscountInterestsFee'
                        , 'type' => 'decimal'
                    ]
                    , 'ReconciliationMatchingRuleSetId' => [
                        'preferred_name' => 'ReconciliationMatchingRuleSetId'
                        , 'type' => 'string'
                    ]
                    , 'AddressCountryISOCode' => [
                        'preferred_name' => 'AddressCountryISOCode'
                        , 'type' => 'string'
                    ]
                    , 'AddressCountry' => [
                        'preferred_name' => 'AddressCountry'
                        , 'type' => 'string'
                    ]
                    , 'ControlInternalNumber' => [
                        'preferred_name' => 'ControlInternalNumber'
                        , 'type' => 'string'
                    ]
                    , 'AddressTimeZone' => [
                        'preferred_name' => 'AddressTimeZone'
                        , 'type' => 'string'
                    ]
                    , 'AccountNumber' => [
                        'preferred_name' => 'AccountNumber'
                        , 'type' => 'string'
                    ]
                    , 'SWIFTCode' => [
                        'preferred_name' => 'SWIFTCode'
                        , 'type' => 'string'
                    ]
                    , 'Name' => [
                        'preferred_name' => 'Name'
                        , 'type' => 'string'
                    ]
                    , 'SortCode' => [
                        'preferred_name' => 'SortCode'
                        , 'type' => 'string'
                    ]
                ]
            ]
            , 'settled_payment' => [
                'internal_name' => 'PaymentJournalLineSettledInvoices'
                , 'fields' => [
                    '_Id' => [
                        'preferred_name' => 'Id'
                        , 'type' => 'formula'
                        , 'formula' => 'strtoupper(\'{InvoiceCompany}\').\'-\'.\'{InvoiceNumber}\''
                        , 'formula_type' => 'string'
                        , 'mandatory' => 1,
                    ]
                    , 'JournalBatchNumber' => [
                        'preferred_name' => 'JournalBatchNumber'
                        , 'type' => 'string'
                    ]
                    , 'JournalLineNumber' => [
                        'preferred_name' => 'JournalLineNumber'
                        , 'type' => 'int'
                    ]
                    , 'InvoiceNumber' => [
                        'preferred_name' => 'Invoice'
                        , 'type' => 'string'
                        , 'relationship' => [
                            'local_field' => 'Invoice'
                            , 'preferred_local_key_name' => 'InvoiceNumber'
                            , 'remote_field' => 'InvoiceNumber'
                            , 'remote_entity' => 'sales_invoice'
                            , 'remote_type' => 'parent'
                        ]
                    ]     
                    , 'InvoiceCompany' => [
                        'preferred_name' => 'InvoiceCompany'
                        , 'type' => 'string'
                    ]
                    , 'InvoiceDueDate' => [
                        'preferred_name' => 'InvoiceDueDate'
                        , 'type' => 'string'
                    ]
                    , 'InvoiceToPaymentCrossRate' => [
                        'preferred_name' => 'InvoiceToPaymentCrossRate'
                        , 'type' => 'decimal'
                    ]
                    , 'SettlementAmountInInvoiceCurrency' => [
                        'preferred_name' => 'AmountSettled'
                        , 'type' => 'decimal'
                    ]
                    , 'CashDiscountToTakeInInvoiceCurrency' => [
                        'preferred_name' => 'CashDiscountToTakeInInvoiceCurrency'
                        , 'type' => 'decimal'
                    ]
                    , 'AccountDisplayValue' => [
                        'preferred_name' => 'AccountDisplayValue'
                        , 'type' => 'string'
                    ] 
                ]
            ]
        ]];

    //     variable_set('D365_DRIVER_OBJECTS', $in_store);
    // }    

    return $in_store;
}
