<?php

module_load_include('module', 'settings_provider');
$module_path = drupal_get_path('module', 'remedy_connection_driver');
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/forms/admin.inc');

if (!class_exists('nusoap_base')) {
    include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/nusoap/nusoap.php');
}

if (!class_exists('nusoap_client')) {
    include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/nusoap/class.soapclient.php');
}

if (!class_exists('nusoap_client')) {
    include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/nusoap/class.soapclient.php');
}
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/BMCRemedyConnectionDriver.php');

use com\mainone\middleware\BMCRemedyConnectionDriver;

function remedy_connection_driver_connection_driver_bmc_remedy_alter(&$container) {
    $connection_settings = remedy_connection_driver__get_settings();
    $driver = new BMCRemedyConnectionDriver(function($x) {
        return mware_connection_driver__get_driver($x);
    }, $connection_settings);

    $defs = remedy_connection_driver__get_entity_definitions();
    $driver->setEntities($defs);
    $container['bmc_remedy'] = $driver;
}


/**
 * Returns the connection settings with which to connect to salesforce.
 * @return \stdClass
 */
function remedy_connection_driver__get_settings($settings = 'default') {
    $s = new stdClass();
    $sT = $settings == 'default' ? variable_get('REMEDY_SETTINGS_USE_PRODUCTION', FALSE) : ($settings == 'production' ? TRUE : FALSE);

    if ($sT == FALSE) {
        $s->URL = variable_get('REMEDY_SANDBOX_SETTINGS_ENDPOINT_URL');
        $s->Username = variable_get('REMEDY_SANDBOX_SETTINGS_USERNAME');
        $s->Password = variable_get('REMEDY_SANDBOX_SETTINGS_PASSWORD');
    } else {
        $s->URL = variable_get('REMEDY_SETTINGS_ENDPOINT_URL');
        $s->Username = variable_get('REMEDY_SETTINGS_USERNAME');
        $s->Password = variable_get('REMEDY_SETTINGS_PASSWORD');
    }
    
    return $s;
}

/**
 * Implements hook_permission
 * @return array
 */
function remedy_connection_driver_permission() {
    $permission = [];

    return $permission;
}

/**
 * Confirms if a user should be allowed to access something.
 * @param type $args
 * @return boolean
 */
function remedy_connection_driver__user_access($args) {
    return true;
}

/**
 * Returns all the entity definitions implemented in Dynamics AX.
 * @return type
 */
function remedy_connection_driver__get_entity_definitions() {
    return [
        'incidentweb' => [
            'internal_name' => 'MainOne:ShowIncidentsWebService'
            , 'soap_methods' => [
                'query' => 'New_GetList_Operation_1'
            ]
            , 'fields' => [
                'Incident_Number' => [
                    'preferred_name' => 'Id'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Submitter' => [
                    'preferred_name' => 'SubmittedBy'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'SubmittedBy'
                        , 'preferred_local_key_name' => 'SubmitterId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                    ]
                ]
                , 'HPD_CI' => [
                    'preferred_name' => 'CI'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'CI'
                        , 'preferred_local_key_name' => 'CircuitID'
                        , 'remote_field' => 'Name'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'customer_product'
                        , 'remote_driver' => 'salesforce'
                    ],
                ]
                , 'Submit_Date' => [
                    'preferred_name' => 'Created'
                    , 'type' => 'datetime'
                ]
                , 'Operational_Categorization_Tier_1' => [
                    'preferred_name' => 'OperationalCategorizationTier1'
                    , 'preferred_query_name' => 'Categorization Tier 1'
                    , 'type' => 'string'
                ]
                , 'Status' => [
                    'preferred_name' => 'Status'
                    , 'type' => 'string'
                ]
                , 'Customer_Login_ID' => [
                    'preferred_name' => 'Customer'
                    , 'type' => 'string'
                ]
                , 'First_Name' => [
                    'preferred_name' => 'FirstName'
                    , 'type' => 'string'
                ]
                , 'Last_Name' => [
                    'preferred_name' => 'LastName'
                    , 'type' => 'string'
                ]
                , 'Description' => [
                    'preferred_name' => 'Description'
                    , 'type' => 'string'
                ]
                , 'IncidentImpact' => [
                    'preferred_name' => 'IncidentImpact'
                    , 'type' => 'string'
                ]
                , 'IncidentStartTime' => [
                    'preferred_name' => 'StartTime'
                    , 'type' => 'datetime'
                ]
                , 'Last_Modified_Date' => [
                    'preferred_name' => 'Modified'
                    , 'preferred_query_name' => 'Last Modified Date'
                    , 'type' => 'datetime'
                ]
                , 'Assignee_Login_ID' => [
                    'preferred_name' => 'AssignedTo'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'AssignedTo'
                        , 'preferred_local_key_name' => 'AssigneeId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                        , 'filter' => 'ObjectClass eq \'person\''
                    ]
                ]
                , '_WorkLog' => [
                    'preferred_name' => 'WorkLog'
                    , 'type' => 'detail'
                    , 'relationship' => [
                        'local_field' => 'Id'
                        , 'remote_field' => 'Incident'
                        , 'remote_type' => 'child'
                        , 'remote_entity' => 'incidentworklog'
                    ]
                ]
            ]
        ]
        , 'incidentworklog' => [
            'internal_name' => 'MainOne_ShowIncidentWorkLogWebService'
            , 'soap_methods' => [
                'query' => 'New_GetList_Operation_0'
            ]
            , 'fields' => [
                'Work_Log_ID' => [
                    'preferred_name' => 'Id'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Incident_Number' => [
                    'preferred_name' => 'Incident'
                    , 'type' => 'string'
                    , 'preferred_query_name' => 'Incident Number'
                    , 'mandatory' => 1
                    , 'relationship' => [
                        'local_field' => 'Incident'
                        , 'preferred_local_key_name' => 'IncidentId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'incidentweb'
                    ]
                ]
                , 'Submitter' => [
                    'preferred_name' => 'SubmittedBy'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'SubmittedBy'
                        , 'preferred_local_key_name' => 'SubmitterId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                    ]
                ]
                , 'Submit_Date' => [
                    'preferred_name' => 'Created'
                    , 'type' => 'string'
                ]
                , 'Status' => [
                    'preferred_name' => 'Status'
                    , 'type' => 'string'
                ]
                , 'Description' => [
                    'preferred_name' => 'Description'
                    , 'type' => 'string'
                ]
                , 'Work_Log_Type' => [
                    'preferred_name' => 'Type'
                    , 'type' => 'string'
                ]
                , 'IncidentStartTime' => [
                    'preferred_name' => 'StartTime'
                    , 'type' => 'datetime'
                ]
                , 'Last_Modified_Date' => [
                    'preferred_name' => 'Modified'
                    , 'preferred_query_name' => 'Last Modified Date'
                    , 'type' => 'datetime'
                ]
                , 'Assignee_Login_ID' => [
                    'preferred_name' => 'AssignedTo'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'AssignedTo'
                        , 'preferred_local_key_name' => 'AssigneeId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                        , 'filter' => 'ObjectClass eq \'person\''
                    ]
                ]
            ]
        ]
        , 'customer-incident' => [
            'internal_name' => 'globalcustomeridwebservice'
            , 'soap_methods' => [
                'query' => 'GetList'
            ]
            , 'fields' => [
                'Request_ID__c' => [
                    'preferred_name' => 'Id'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Submitter__c' => [
                    'preferred_name' => 'SubmittedBy'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'SubmittedBy'
                        , 'preferred_local_key_name' => 'SubmitterId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                    ],
                ]
                , 'Submit_Date' => [
                    'preferred_name' => 'Submitted'
                    , 'type' => 'string'
                ]
                , 'Assignee_Login_ID' => [
                    'preferred_name' => 'AssignedTo'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'AssignedTo'
                        , 'preferred_local_key_name' => 'AssigneeId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                        , 'filter' => 'ObjectClass eq \'person\''
                    ],
                ]
            ]
        ]
        , 'incident' => [
            'internal_name' => 'HPD_IncidentInterface_WS'
            , 'soap_methods' => [
                'query' => 'HelpDesk_QueryList_Service'
            ]
            , 'fields' => [
                'Entry_ID' => [
                    'preferred_name' => 'Id'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Submitter' => [
                    'preferred_name' => 'SubmittedBy'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'SubmittedBy'
                        , 'preferred_local_key_name' => 'SubmitterId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                    ],
                ]
                , 'Submit_Date' => [
                    'preferred_name' => 'Submitted'
                    , 'type' => 'string'
                ]
                , 'Last_Modified_Date' => [
                    'preferred_name' => 'Modified'
                    , 'preferred_query_name' => '\'Last Modified Date\''
                    , 'type' => 'string'
                ]
                , 'Assignee_Login_ID' => [
                    'preferred_name' => 'AssignedTo'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'AssignedTo'
                        , 'preferred_local_key_name' => 'AssigneeId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                        , 'filter' => 'ObjectClass eq \'person\''
                    ],
                ]
            ]
        ]
        , 'asset' => [
            'internal_name' => 'MSDynamics_Remedy'
            , 'soap_methods' => [
                'create' => 'OpCreate'
                , 'query' => 'OpGet'
            ]
            , 'fields' => [
                'Request_ID' => [
                    'preferred_name' => 'Id'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Serial_Number__c' => [
                    'preferred_name' => 'SerialNumber'
                    , 'type' => 'string'
                ]
                , 'Region__c' => [
                    'preferred_name' => 'Region'
                    , 'type' => 'string'
                ]
                , 'Name__c' => [
                    'preferred_name' => 'Name'
                    , 'type' => 'string'
                ]
                , 'Building__c' => [
                    'preferred_name' => 'Building'
                    , 'type' => 'string'
                ]
                , 'Floor__c' => [
                    'preferred_name' => 'Floor'
                    , 'type' => 'string'
                ]
                , 'Room__c' => [
                    'preferred_name' => 'Room'
                    , 'type' => 'string'
                ]
                , 'Item_Group__c' => [
                    'preferred_name' => 'ItemGroup'
                    , 'type' => 'string'
                ]
                , 'Item_Number__c' => [
                    'preferred_name' => 'ItemNumber'
                    , 'type' => 'string'
                ]
                , 'Pallet_ID__c' => [
                    'preferred_name' => 'PalletID'
                    , 'type' => 'string'
                ]
                , 'Size__c' => [
                    'preferred_name' => 'Size'
                    , 'type' => 'string'
                ]
                , 'Warehouse__c' => [
                    'preferred_name' => 'Warehouse'
                    , 'type' => 'string'
                ]
                , 'Site__c' => [
                    'preferred_name' => 'Site'
                    , 'type' => 'string'
                ]
                , 'MainOne_Site__c' => [
                    'preferred_name' => 'MainOneSite'
                    , 'type' => 'string'
                ]
                , 'Batch_Number__c' => [
                    'preferred_name' => 'BatchNumber'
                    , 'type' => 'string'
                ]
                , 'Asset_Description__c' => [
                    'preferred_name' => 'AssetDescription'
                    , 'type' => 'string'
                ]
                , 'TotalAvailable__c' => [
                    'preferred_name' => 'TotalAvailable'
                    , 'type' => 'string'
                ]
                , 'PhysicalReserved__c' => [
                    'preferred_name' => 'PhysicalReserved'
                    , 'type' => 'string'
                ]
                , 'OrderedReserved__c' => [
                    'preferred_name' => 'OrderedReserved'
                    , 'type' => 'string'
                ]
                , 'On_Order__c' => [
                    'preferred_name' => 'OnOrder'
                    , 'type' => 'string'
                ]
                , 'Ordered__c' => [
                    'preferred_name' => 'Ordered'
                    , 'type' => 'string'
                ]
                , 'Physical_Inventory__c' => [
                    'preferred_name' => 'PhysicalInventory'
                    , 'type' => 'string'
                ]
            ]
        ]
        , 'people' => [
            'internal_name' => 'MainOne_GNOC_CustomerClientService'
            , 'soap_methods' => [
                'create' => 'CreateClientService_Operation'
                , 'query' => 'GetAllClientServices_Operation'
            ]
            , 'fields' => [
                'Request_ID' => [
                    'preferred_name' => 'Id'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Create_Date' => [
                    'preferred_name' => 'Created'
                    , 'type' => 'datetime'
                ]
                , 'Modified_Date' => [
                    'preferred_name' => 'Modified'
                    , 'type' => 'datetime'
                ]
                , 'Last_Modified_By' => [
                    'preferred_name' => 'ModifiedBy'
                    , 'type' => 'string'
                    , 'mandatory' => 1
                    , 'relationship' => [
                        'local_field' => 'ModifiedBy'
                        , 'preferred_local_key_name' => 'ModifiedById'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                        , 'filter' => 'ObjectClass eq \'person\''
                    ]
                ]
                , 'Status' => [
                    'preferred_name' => 'Status'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Switch' => [
                    'preferred_name' => 'Switch'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Service_CI_Type' => [
                    'preferred_name' => 'Type'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Service_Account_Name' => [
                    'preferred_name' => 'ServiceAccountName'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Service_Account_ID' => [
                    'preferred_name' => 'ServiceAccountId'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Circuit_Capacity' => [
                    'preferred_name' => 'CircuitCapacity'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Product' => [
                    'preferred_name' => 'Product'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Start_Date' => [
                    'preferred_name' => 'StartDate'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Service_CI' => [
                    'preferred_name' => 'Name'
                    , 'type' => 'string'
                ]
                , 'Customer_Name' => [
                    'preferred_name' => 'CustomerId'
                    , 'type' => 'string'
                ]
                , 'PoP_Location' => [
                    'preferred_name' => 'PoPLocation'
                    , 'type' => 'string'
                ]
                , 'First_Name' => [
                    'preferred_name' => 'FirstName'
                    , 'type' => 'string'
                ]
                , 'Last_Name' => [
                    'preferred_name' => 'LastName'
                    , 'type' => 'string'
                ]
                , 'Customer_ID' => [
                    'preferred_name' => 'CustomerId'
                    , 'type' => 'string'
                ]
                , 'Customer_Escalation_List' => [
                    'preferred_name' => 'CustomerEscalationList'
                    , 'type' => 'string'
                ]
            ]
        ]
        , 'serviceaccount' => [
            'internal_name' => 'MainOne_GNOC_CustomerServiceAccount'
            , 'soap_methods' => [
                'create' => 'CreateServiceAccount_Operation'
                , 'query' => 'GetAllAccounts_Operation'
            ]
            , 'fields' => [
                'Request_ID' => [
                    'preferred_name' => 'Id'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Create_Date' => [
                    'preferred_name' => 'Created'
                    , 'type' => 'datetime'
                ]
                , 'Modified_Date' => [
                    'preferred_name' => 'Modified'
                    , 'type' => 'datetime'
                ]
                , 'Last_Modified_By' => [
                    'preferred_name' => 'ModifiedBy'
                    , 'type' => 'string'
                    , 'mandatory' => 1
                    , 'relationship' => [
                        'local_field' => 'ModifiedBy'
                        , 'preferred_local_key_name' => 'ModifiedById'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                        , 'filter' => 'ObjectClass eq \'person\''
                    ]
                ]
                , 'Status' => [
                    'preferred_name' => 'Status'
                    , 'type' => 'string'
                ]
                , 'Short_Description' => [
                    'preferred_name' => 'ShortDescription'
                    , 'type' => 'string'
                ]
                , 'Status_History' => [
                    'preferred_name' => 'StatusHistory'
                    , 'type' => 'string'
                ]
                , 'Customer_Name' => [
                    'preferred_name' => 'CustomerName'
                    , 'preferred_query_name' => 'Customer_Name__c'
                    , 'type' => 'string'
                ]
                , 'Service_Account_Name__c' => [
                    'preferred_name' => 'Name'
                    // , 'preferred_query_name' => 'Service_Account_Name'
                    , 'type' => 'string'
                ]
                , 'Escalation_List__c' => [
                    'preferred_name' => 'EscalationList'
                    , 'preferred_query_name' => 'Escalation_List'
                    , 'type' => 'string'
                ]
                , 'First_Name' => [
                    'preferred_name' => 'FirstName'
                    , 'type' => 'string'
                ]
                , 'Last_Name' => [
                    'preferred_name' => 'LastName'
                    , 'type' => 'string'
                ]
                , 'id_OLD__c' => [
                    'preferred_name' => 'OldId'
                    , 'type' => 'string'
                ]
                , 'Customer_ID__c' => [
                    'preferred_name' => 'CustomerId'
                    , 'type' => 'string'
                ]
                , 'Flag' => [
                    'preferred_name' => 'Flag'
                    , 'type' => 'string'
                ]
                , 'id_Country__c' => [
                    'preferred_name' => 'CountryId'
                    , 'type' => 'string'
                ]
                , 'str_SATownAddress' => [
                    'preferred_name' => 'SATownAddress'
                    , 'type' => 'string'
                ]
            ]
        ]
        , 'service' => [
            'internal_name' => 'MainOne_GNOC_CustomerClientServices'
            , 'soap_methods' => [
                'create' => 'CreateClientService_Operation'
                , 'query' => 'GetAllClientServices_Operation'
            ]
            , 'fields' => [
                'Request_ID' => [
                    'preferred_name' => 'Id'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Create_Date' => [
                    'preferred_name' => 'Created'
                    , 'type' => 'datetime'
                ]
                , 'Modified_Date' => [
                    'preferred_name' => 'Modified'
                    , 'type' => 'datetime'
                ]
                , 'Last_Modified_By' => [
                    'preferred_name' => 'ModifiedBy'
                    , 'type' => 'string'
                    , 'mandatory' => 1
                    , 'relationship' => [
                        'local_field' => 'ModifiedBy'
                        , 'preferred_local_key_name' => 'ModifiedById'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'objects'
                        , 'remote_driver' => 'ldap'
                        , 'filter' => 'ObjectClass eq \'person\''
                    ]
                ]
                , 'Status' => [
                    'preferred_name' => 'Status'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Switch' => [
                    'preferred_name' => 'Switch'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Service_CI_Type' => [
                    'preferred_name' => 'Type'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Service_Account_Name' => [
                    'preferred_name' => 'ServiceAccountName'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Service_Account_ID' => [
                    'preferred_name' => 'ServiceAccount'
                    , 'type' => 'string'
                    , 'relationship' => [
                        'local_field' => 'ServiceAccount'
                        , 'preferred_local_key_name' => 'ServiceAccountId'
                        , 'remote_field' => 'Id'
                        , 'remote_type' => 'parent'
                        , 'remote_entity' => 'serviceaccount'
                    ]
                ]
                , 'Circuit_Capacity' => [
                    'preferred_name' => 'CircuitCapacity'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Product' => [
                    'preferred_name' => 'Product'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Start_Date' => [
                    'preferred_name' => 'StartDate'
                    , 'type' => 'string'
                    , 'mandatory' => 1,
                ]
                , 'Service_CI' => [
                    'preferred_name' => 'Name'
                    , 'type' => 'string'
                ]
                , 'Customer_Name' => [
                    'preferred_name' => 'CustomerId'
                    , 'type' => 'string'
                ]
                , 'PoP_Location' => [
                    'preferred_name' => 'PoPLocation'
                    , 'type' => 'string'
                ]
                , 'First_Name' => [
                    'preferred_name' => 'FirstName'
                    , 'type' => 'string'
                ]
                , 'Last_Name' => [
                    'preferred_name' => 'LastName'
                    , 'type' => 'string'
                ]
                , 'Customer_ID' => [
                    'preferred_name' => 'CustomerId'
                    , 'type' => 'string'
                ]
                , 'Customer_Escalation_List' => [
                    'preferred_name' => 'EscalationList'
                    , 'type' => 'string'
                ]
            ]
        ]
    ];
}