<?php

module_load_include('module', 'settings_provider');
$module_path = drupal_get_path('module', 'net_boss_connection_driver');
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/forms/admin.inc');
include_once str_replace('/', DIRECTORY_SEPARATOR, $module_path . '/NetBossConnectionDriver.php');

use com\mainone\middleware\NetBossConnectionDriver;

function net_boss_connection_driver_connection_driver_netboss_alter(&$container)
{
    $driver = new NetBossConnectionDriver(function ($x) {
        $return = mware_connection_driver__get_driver($x);
        return $return;
    }, function ($source_name) {
        return net_boss_connection_driver__get_settings($source_name);
    }, 'netboss');

    $defs = net_boss_connection_driver__get_entity_definitions_local();
    $driver->setEntities($defs);
    $container['netboss'] = $driver;
}

function net_boss_connection_driver__get_settings($key)
{
    $settings = new \stdClass();

    $settings->DSN = variable_get("SQL_SETTINGS_DSN_{$key}");
    $settings->Username = variable_get("SQL_SETTINGS_USERNAME_{$key}");
    $settings->Password = variable_get("SQL_SETTINGS_PASSWORD_{$key}");
    $settings->DatabaseType = variable_get("SQL_SETTINGS_DBTYPE_{$key}");

    return $settings;
}

/**
 * Implements hook_permission
 * @return array
 */
function net_boss_connection_driver_permission()
{
    $permission = [];

    return $permission;
}

/**
 * Confirms if a user should be allowed to access something.
 * @param type $args
 * @return boolean
 */
function net_boss_connection_driver__user_access($args)
{
    return true;
}
/**
 * 
 * Returns entity definitions that have been marked as cacheable to the specified entity.
 *
 * @param String $targetDriver the connection driver to use to retrieve the cache.
 * @return void
 */
function snet_boss_connection_driver__get_cached_entity_definitions($targetDriver)
{
    return settings_provider__format_cached_definition('netboss', $targetDriver, function(){
        $args = func_get_args();
        $return = net_boss_connection_driver__get_entity_definitions_local(...$args);
        return $return;
    });
}

function net_boss_connection_driver__get_entity_definitions_local(){
    return net_boss_connection_driver__get_entity_definitions(...func_get_args())['netboss'];
}

/**
 * Returns all the entity definitions implemented in Dynamics AX.
 * @return type
 */
function net_boss_connection_driver__get_entity_definitions()
{
    $return = ['netboss'=>[
        'devices' => [
            'internal_name' => 'CustomerDictionary'
            , 'datasource' => 'default'
            , 'fields' => [
                'ID' => [
                    'preferred_name' => 'Id'
                    , 'type' => 'int'
                    , 'mandatory' => 1,
                ]
            ]
        ]  ]      
    ];

    // Add other entities that have been cached to this driver.
    // $cached_all = module_invoke_all('_get_cached_entity_definitions', 'netboss');
    // foreach ($cached_all as $cached) {
    //     $g = is_null($cached)?[]:$cached;
    //     $return = array_merge($return, $g);
    // }

    return $return;
}
